version: '3.8'
services:
  backend:
    build: ./faq-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_REDIS_HOST: redis

  frontend:
    build: ./faq-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://backend:8080

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"